Migrerer til GCP

diff --git a/.github/workflows/deploy.prod-sbs.yml b/.github/workflows/deploy.prod-sbs.yml
--- a/.github/workflows/deploy.prod-sbs.yml
+++ b/.github/workflows/deploy.prod-sbs.yml
@@ -1,12 +1,16 @@
-name: Deploy-to-dev
+name: Deploy-to-prod
 on:
-  workflow_dispatch
+  release:
+    types: [released]
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v1
+      - uses: actions/checkout@v2
+      - name: Abort if branch is not master
+        if: github.event.release.target_commitish != 'master'
+        run: echo "Release is not on master, aborting"; exit 1;
       - name: Define build environment
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -28,31 +32,31 @@ jobs:
       - name: Docker build and push
         run: |
           echo $GITHUB_TOKEN | docker login $IMAGE_REGISTRY -u ${GITHUB_REPOSITORY} --password-stdin
-          docker build -t $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION .
-          docker push $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
+          docker build -t $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION -t $IMAGE_REGISTRY/$IMAGE_NAME:latest .
+          docker push $IMAGE_REGISTRY/$IMAGE_NAME --all-tags
       - name: Generate nais variables
         run: |
           cat > .nais/vars.yaml <<EOF
           namespace: personbruker
           ingresses:
-            - https://www.dev.nav.no/person/kontakt-oss/nb/tilbakemeldinger
-            - https://www.dev.nav.no/person/kontakt-oss/en/tilbakemeldinger
-            - https://www.dev.nav.no/person/kontakt-oss/tilbakemeldinger
-            - https://www.dev.nav.no/person/kontakt-oss/nb/finnkontor
-            - https://www.dev.nav.no/person/kontakt-oss/en/finnkontor
-            - https://www.dev.nav.no/person/kontakt-oss/finnkontor
-            - https://www.dev.nav.no/person/kontakt-oss/nb/samegiella
-            - https://www.dev.nav.no/person/kontakt-oss/en/samegiella
-            - https://www.dev.nav.no/person/kontakt-oss/samegiella
-            - https://www.dev.nav.no/person/kontakt-oss/nb/chat
-            - https://www.dev.nav.no/person/kontakt-oss/en/chat
-            - https://www.dev.nav.no/person/kontakt-oss/chat
+            - https://www.nav.no/person/kontakt-oss/nb/tilbakemeldinger
+            - https://www.nav.no/person/kontakt-oss/en/tilbakemeldinger
+            - https://www.nav.no/person/kontakt-oss/tilbakemeldinger
+            - https://www.nav.no/person/kontakt-oss/nb/finnkontor
+            - https://www.nav.no/person/kontakt-oss/en/finnkontor
+            - https://www.nav.no/person/kontakt-oss/finnkontor
+            - https://www.nav.no/person/kontakt-oss/nb/samegiella
+            - https://www.nav.no/person/kontakt-oss/en/samegiella
+            - https://www.nav.no/person/kontakt-oss/samegiella
+            - https://www.nav.no/person/kontakt-oss/nb/chat
+            - https://www.nav.no/person/kontakt-oss/en/chat
+            - https://www.nav.no/person/kontakt-oss/chat
           image: $IMAGE_REGISTRY/$IMAGE_NAME
           version: $IMAGE_VERSION
           EOF
       - uses: nais/deploy/actions/deploy@master
         env:
-          CLUSTER: dev-gcp
+          CLUSTER: prod-sbs
           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
-          RESOURCE: .nais/config-dev.yaml
+          RESOURCE: .nais/config-prod.yaml
           VARS: .nais/vars.yaml
diff --git a/.github/workflows/deploy.prod.yml b/.github/workflows/deploy.prod.yml
--- a/.github/workflows/deploy.prod.yml
+++ b/.github/workflows/deploy.prod.yml
@@ -1,21 +1,16 @@
 name: Deploy-to-prod
 on:
-  push:
-    tags:
-      - "v*-prod"
-      - "!v*-dev*"
-      - "!v*-test*"
+  release:
+    types: [released]
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - run: git fetch --prune --unshallow
-      - name: Check if tag exists on master
-        run: |
-          if git branch -r --contains ${GITHUB_REF##*/} | grep master>/dev/null 2>&1
-          then echo "Tag ${GITHUB_REF##*/} verified on master";
-          else echo "Tag ${GITHUB_REF##*/} not found on master"; exit 1; fi
+      - name: Abort if branch is not master
+        if: github.event.release.target_commitish != 'master'
+        run: echo "Release is not on master, aborting"; exit 1;
       - name: Define build environment
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -26,7 +21,7 @@ jobs:
           echo "IMAGE_NAME=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_ENV
           echo "IMAGE_VERSION=${IMAGE_VERSION_RAW,,}" >> $GITHUB_ENV
           echo "GITHUB_TOKEN=$(echo ${GITHUB_TOKEN})" >> $GITHUB_ENV
-      - uses: actions/cache@v1
+      - uses: actions/cache@v2
         with:
           path: ~/.npm
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
@@ -61,7 +56,7 @@ jobs:
           EOF
       - uses: nais/deploy/actions/deploy@master
         env:
-          CLUSTER: prod-sbs
+          CLUSTER: prod-gcp
           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
           RESOURCE: .nais/config-prod.yaml
           VARS: .nais/vars.yaml
